import "./globals.css";

import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import Link from "next/link";

import AuthButtons from "@/components/auth-buttons";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/auth-context";

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "700"], // 一般的なweightだけに制限
  display: "swap",
  preload: false, // プリロードを無効化
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.className} antialiased`}>
        <AuthProvider>
          <nav className="bg-primary text-white p-5 h-24 flex items-center justify-between fixed top-0 left-0 right-0 z-50">
            <Link
              href="/login"
              className="text-3xl tracking-widest flex gap-2 items-center uppercase"
            >
              <span>MOBILE ORDER MANAGER</span>
            </Link>
            <ul className="flex gap-6 items-center">
              {/* <li>
                <Link
                  href="products"
                  className="tracking-widest hover:underline"
                >
                  Products List
                </Link>
              </li> */}
              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {/* ヘッダーの高さ分のパディングを追加 dashboardのlayout.tsxと重ならないようにする*/}
          <div className="pt-24">{children}</div>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
